# Generated by Django 5.2.5 on 2025-09-21 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_g_p_a_student_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='student',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
