# Generated by Django 5.2.5 on 2025-09-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_image_student_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='uploaded_at',
        ),
    ]
